version: '3.3'
services:
    app:
        image: afsanarozan/exam:v1
        ports:
            - 8080:8080
        networks:
            - deploy
        environment: 
            - APP_NAME=pingpong-app
            - PORT=8080

networks:
    deploy:
