---
apiVersion: v1
kind: Namespace
metadata:
    name: test
---
apiVersion: v1
data:
    APP_NAME: "pingpong-app"
    PORT: "8080"
    KAFKA_BROKER: "kafka.kafka:9092" 

kind: ConfigMap
metadata:
    name: env-pingpong
    namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pingpong-app
    namespace: test
spec:
    replicas: 2
    selector:
      matchLabels:
        app: pingpong-apps
    template:
      metadata:
        labels:
          app: pingpong-apps
      spec: 
        containers:
        - name: pingpong-apps
          image: afsanarozan/kmprn-exam:consumer
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: env-pingpong
---
apiVersion: v1
kind: Service
metadata:
    name: pingpong-service
    namespace: test
    labels:
      app: pingpong-services
spec:
    selector:
      app: pingpong-apps
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        name: serviceport
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#     name: nginx-ingress
#     labels:
#       name: nginx-ingress
#     namespace: pingpong
# spec:
#   rules:
#     - host: pingpong.afsanarozannaufal.site
#       http:
#         paths:
#          - backend:
#             serviceName: pingpong-service
#             servicePort: 80
